apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  labels:
    app: streamlit
spec:
  selector:
    app: streamlit
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8501
  type: ClusterIP